---
active_modules: [pygments, tags, blog, latex]
author: Benji Lee
canonical_url: http://www.empty.com
modules:
  pygments:
    style: tango
ignore_files: [venv, .vscode, .git, .gitignore, '.*', '_*', 'config.yml', 'Makefile', 'README', '*.conf']